### ISSUE TITLE
Warning when adding an item to the cart

### ISSUE THREAD

**Issue by hugotox** [eggheadio/egghead-react-flux-example#10]
Issue happens when you visit the cart route, then go back to the index page and every time you add an item to the cart this warning is generated:
```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.
```

**Comment by hugotox** [comment]
Sorry it was identified in the next lesson

**Comment by hugotox** [comment]
it keeps happening even after adding `componentWillUnMount` from https://egghead.io/lessons/react-react-flux-remove-duplicate-code-with-mixins lesson

**Comment by fdelacruz** [comment]
Hi, was this resolved??
