### ISSUE TITLE
react/lib/merge has been deprecated

### ISSUE THREAD

**Issue by urbanvikingr** [eggheadio/egghead-react-flux-example#9]
It seems that the example hasn't been updated for a while. I'm a great fan of the egggead.io tutorials, but it is a shame the code isn't maintained.

Please make a note on the tutorials, if you aren't planning on keeping the code up-to-date. I would also recommend make this series free, if the code isn't following the latest recommendations.

Other changes:
The /** @jsx React.DOM */ header is no longer required when writing JSX syntax.

ES6:
import React from "react" instead of require
class App extends React.Component instead of createClass

**Comment by joelhooks** [comment]
Thanks for the tips! The code has been updated :flushed:

**Comment by rkhayat** [comment]
I ran across this while googling for React Merge, from this tutorial- ```https://scotch.io/tutorials/getting-to-know-flux-the-react-js-architecture

**Comment by Olgagr** [comment]
It seems like now instead of using merge module, we should use react-addons-update and $merge command.
